from tkinter import *
root=Tk()
root.title("Login app")
root.geometry("400x300")
frame=Frame(master=root,height=200,width=300,bg='white')
lbl1=Label(frame,text="Full Name", bg='white')
lbl2=Label(frame,text="Email", bg='white')
lbl3=Label(frame,text="Password", bg='white')
name_entry=Entry(frame)
email_entry=Entry(frame)
password_entry=Entry(frame)
def display():
    name=name_entry.get()
    greet="Hello "+name
    message="\nCongratulations"
    textbox.insert(END,greet)
    textbox.insert(END,message)
textbox=Text(bg='white',fg="black")
btn=Button(text="Create Account", command=display, bg="light blue")
frame.place(x=20,y=0)
lbl1.place(x=20, y=20)
name_entry.place(x=150, y=20)
lbl2.place(x=20, y=80)
email_entry.place(x=150, y=80)
lbl3.place(x=20, y=140)
password_entry.place(x=150, y=140)
btn.place(x=130, y=210)
textbox.place(y=250)
root.mainloop()