import math
print(math.ceil(4.2))
print(math.floor(4.8))
print(math.fabs(-7.5))
print(math.factorial(5))
print(math.pow(2,3))
print(math.sqrt(64))
print(math.log(10))
print(math.log10(10))
radians=math.radians(90)
print(radians)
print(math.sin(radians))
print(math.pi)
print(math.pi)
print(math.e)
print(math.gcd(24,36))